language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
script:
- npm run build
after_script:
- cd ./public
- git init
- git config user.name "travis upload"
- git config user.email "285516193@qq.com"
- git add .
- git commit -m "Update docs"
- git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" origin/gh-pages
branches:
  only:
  - master
git:
  depth: 1
env:
  global:
  - GH_REF: github.com/cexoso/cexoso.git
  - secure: aW7TcVFDWhDTuEDPxLM9OZL0c4p3Pc/qqqg2xAU+TgHoy81wQYIzcxzxM5ayB7iMOSE4tQiTkz3JfzLZ7C+9U1ojw8cktLzFly6XORU1rNN89K4W5EIhmjlVunUKvRISORfpfdt8hZBOT6VBuAjquFqOWh3vZ73jlVde8cUw7LJF41ilMVOR+s5X/cs0qboZLXBADdVbrP5TWimi4744GHmtO0bTTOPWuUUSPrXyZSUKMZswxILNN5z4aJjH9fvLbCMkXp4xAfn07RZNmICmuaCA6Dj2rkPTvhf4v4IApRBXV1QiIQzymMUTU6Nce6PW3nIao5iyRr3IjR7OHOAGpB5uoAgOxT+4YhuULwoCDcNwi29xeGSQWH2FFtyJEhZEzPnKfpXta7Pwd3UFdcdiJEzxYWtToBMiLIjKPJ09Bu6BnRO36NvE/2PFPfd/x/kQ1ajjyi9MIMZKwks5a1SRboeY/bwW7nHqJC3avWehTMlcafVPddiEEWB6rlNzSox6gRmukAh5ozKm4u1J0o2kqHleOMiZ6dnD2yAL7ln85rxQz9qe5DmAWO3VppZSooDUrFjTohT7g1CvhNFp9aVNrdQg3n8+D0q0ygkj75wOlLqQUMAehGMQTpUUdB77/b90fwv+0a3/U8qZFjhRj+5qezfKB3p5R3eC0Gv+KFWKUO8=
